services:
  db:
    image: postgres:17-alpine
    container_name: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${HOME}/.var/postgresql/${POSTGRES_DB}/data:/var/lib/postgresql/data
